### PR TITLE
fix non-deterministic test

### LINKED ISSUE #3: Intermittent RSpec failure with rack handler specs
I've not isolated this yet, but I'm sure it's a timing issue 

```
➜  zipkin-tracer git:(unreliable-specs) ✗ be rake spec
/home/tyler/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/lib:/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-support-3.0.4/lib -S /home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/exe/rspec ./spec/rack_handler_spec.rb
........

Finished in 0.01552 seconds (files took 0.11713 seconds to load)
8 examples, 0 failures

Randomized with seed 46989

➜  zipkin-tracer git:(unreliable-specs) ✗ be rake spec
/home/tyler/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/lib:/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-support-3.0.4/lib -S /home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/exe/rspec ./spec/rack_handler_spec.rb
....F...

Failures:

  1) ZipkinTracer::RackHandler configured without plugins with sample rate set to 0 does not sample a request
     Failure/Error: expect(trace_id.sampled?).to be_falsy
       expected: falsey value
            got: true
     # ./spec/rack_handler_spec.rb:45:in `block (5 levels) in <top (required)>'
     # ./lib/zipkin-tracer.rb:88:in `block in tracing_filter'
     # ./lib/zipkin-tracer.rb:87:in `synchronize'
     # ./lib/zipkin-tracer.rb:87:in `tracing_filter'
     # ./lib/zipkin-tracer.rb:70:in `call'
     # ./spec/rack_handler_spec.rb:47:in `block (4 levels) in <top (required)>'

Finished in 0.01555 seconds (files took 0.12222 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/rack_handler_spec.rb:43 # ZipkinTracer::RackHandler configured without plugins with sample rate set to 0 does not sample a request

Randomized with seed 50368

/home/tyler/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/lib:/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-support-3.0.4/lib -S /home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/exe/rspec ./spec/rack_handler_spec.rb failed
➜  zipkin-tracer git:(unreliable-specs) ✗ 
```

### PR DESCRIPTION
**Pull request by jamescway**
* add .gitignore
* add pry as dev dep
* fix the test which was intermittently failing.  Traced this to finagle-thrift method `should_sample?` method which had a rand in it.  Stubbed it out.

Fixes #3

### CODE REVIEW

File: spec/rack_handler_spec.rb [hunk 1]
```diff
@@ -126,6 +126,7 @@ def mock_env(path = '/', params = {})
       subject { middleware(app, :whitelist_plugin => lambda {|env| false}) }
 
       it 'does not sample the request' do
+        allow(::Trace).to receive(:should_sample?) { false }
```
Comment (adriancole) [inline spec/rack_handler_spec.rb]: nit: put comment about rand here

**Comment by adriancole** [comment]
LGTM
